tar:
    #!/bin/bash
    #podman pull fj0rd/scratch:arrow
    o=$PWD
    mkdir -p $o/assets/temp
    mkdir -p $o/assets/dist
    mkdir -p $o/assets/lib
    podman save fj0rd/scratch:arrow | tar -xf - -C $o/assets/temp

    cd $o/assets/temp
    tar -xf $(cat $o/assets/temp/manifest.json | jq -r '.[0].Layers[0]') -C $o/assets/dist --strip-components=2
    tar -xf $(cat $o/assets/temp/manifest.json | jq -r '.[0].Layers[1]') -C $o/assets/dist --strip-components=2
    cd $o/assets/dist
    tar zcvf $o/assets/libarrow-dev.tar.gz *

    cd $o/assets/temp
    tar -xf $(cat $o/assets/temp/manifest.json | jq -r '.[0].Layers[2]') -C $o/assets/lib --strip-components=2
    cd $o/assets/lib
    tar zcvf $o/assets/libarrow.tar.gz *

    rm -rf $o/assets/temp
    rm -rf $o/assets/dist
    rm -rf $o/assets/lib

