name: dropbear

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main, dropbear ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fj0r/scratch


jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.event.head_commit.message, '~') }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: fj0r
          password: ${{ secrets.GHCR_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action

      - name: Build dropbear
        uses: docker/build-push-action@v3
        with:
          context: dropbear
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dropbear
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build dropbear alpine
        uses: docker/build-push-action@v3
        with:
          context: dropbear
          file: dropbear/alpine.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dropbear-alpine
          labels: ${{ steps.meta.outputs.labels }}

      #- name: trigger io:base
      #  run: |
      #    for a in base; do
      #      curl -L -X POST https://api.github.com/repos/fj0r/io/actions/workflows/${a}.yml/dispatches \
      #        -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
      #        -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
      #        -d '{"ref":"main","inputs":{}}'
      #    done


      - name: Delete untagged ghcr
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          # Personal access token (PAT) used to fetch the repository. The PAT is configured
          # with the local git config, which enables your scripts to run authenticated git
          # commands. The post-job step removes the PAT.
          # needs delete:packages permissions
          # required: true
          # [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
          token: ${{ secrets.GHCR_TOKEN }}
          # Repository name or  name with owner
          # Delete only from repository name
          # Default: ${{ github.repository }}
          repository: ${{ github.repository }}
          # 'The repository owner name'
          # Default: ${{ github.repository_owner }}
          repository_owner: ${{ github.repository_owner }}
          # 'The package names'
          # Delete only from comma separated package names
          # required: false
          package_name: ''
          # Delete only package versions without tag
          # required: false
          # Default: true
          # choices: true, false
          untagged_only: true
          # Except untagged multiplatform packages from deletion
          # only for untagged_only=true
          # needs docker installed
          except_untagged_multiplatform: false
          # the owner type
          # required: true
          # choices: org, user
          owner_type: user
